      REAL*8 p_kscale,p_stmin,p_et,p_bs,p_roff,p_pet,p_fprob,p_rootfr
      REAL*8 p_stemfr,p_resp,p_smbbc,p_sla,p_nu1,p_nu2
      REAL*8 p_nu3,p_nu4,p_nleaf,p_dresp,p_vm,p_kgw,p_v1,p_v2,p_v3
      REAL*8 p_v4,p_j1,p_j2,p_j3,p_j4,p_roff2,p_city_dep,p_opt
      REAL*8 p_laimem,p_silt,p_sand,p_bulk,p_orgc,p_awl(4),p_bc_res
      REAL*8 p_kx,p_kd,p_dep,p_topsl

      COMMON/param/p_kscale,p_rootfr,p_stemfr,p_sla,p_stmin,p_resp,
     &p_smbbc,p_et,p_bs,p_roff,p_pet,p_fprob,p_nu1,
     &p_nu2,p_nu3,p_nu4,p_nleaf,p_vm,p_dresp,p_kgw,p_v1,p_v2,p_v3,
     &p_v4,p_j1,p_j2,p_j3,p_j4,p_roff2,p_city_dep,p_opt,p_laimem,
     &p_silt,p_sand,p_bulk,p_orgc,p_awl,p_bc_res,p_kx,p_kd,
     &p_dep,p_topsl
*----------------------------------------------------------------------*
