sdgvm: veg_dynamics Module Reference
veg_dynamics Module Reference
Public Member Functions
subroutine cover (nft, tmp, prc, firec, fireres, fprob, ftprop, check_closure)
subroutine initialise_new_cohorts (nft, ftprop, check_closure)
subroutine growth (nft, lai, stembio, rootbio, check_closure)
subroutine thin (nft, npp, lai, nps, evp, slc, check_closure)
real(dp) function find (tmp, prc)
subroutine c3c42 (ftprop, npp, range)
subroutine c3c4 (ftprop, c3old, c4old, npp, nps)
subroutine grassrec (nft, ftprop, gold, x, nat_map)
subroutine barerec (ftprop, bpaold, x)
subroutine addbio (npp, nps, npr)
subroutine perc (fttags, dof, tmin, ftprop, nft)
subroutine mklit (ftmat, slc, rlc, sln, rln, npp, nps, npr)
real(dp) function stlit (age, mat)
subroutine vegmat (nft, ftmor, ftwd, ftxyl, ftpd, evp, lai, npp, nps, ftmat)
subroutine fire (dprc, dtmp, fri, fprob)
subroutine newgrowth (fprob, npp, nps, fireres, firec)
subroutine natural_veg (tmp, prc, ftprop, nat_map)
Detailed Description
Definition at line 1 of file veg_dynamics.f90.
Member Function/Subroutine Documentation
subroutine veg_dynamics::addbio (real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) nps, real(dp), dimension(max_cohorts) npr)
Definition at line 763 of file veg_dynamics.f90.
subroutine veg_dynamics::barerec (real(dp), dimension(max_cohorts) ftprop, real(dp) bpaold, real(dp) x)
Definition at line 730 of file veg_dynamics.f90.
subroutine veg_dynamics::c3c4 (real(dp), dimension(max_cohorts) ftprop, real(dp) c3old, real(dp) c4old, real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) nps)
Definition at line 638 of file veg_dynamics.f90.
Referenced by doly::dolyday().
subroutine veg_dynamics::c3c42 (real(dp), dimension(max_cohorts) ftprop, real(dp), dimension(max_cohorts) npp, real(dp) range)
Definition at line 612 of file veg_dynamics.f90.
subroutine veg_dynamics::cover (integer nft, real(dp), dimension(12,31) tmp, real(dp), dimension(12,31) prc, real(dp) firec, integer fireres, real(dp) fprob, real(dp), dimension(max_cohorts) ftprop, logical check_closure)
Definition at line 21 of file veg_dynamics.f90.
References fire(), newgrowth(), and state_methods::sum_carbon().
Referenced by sdgvm().
real(dp) function veg_dynamics::find (real(dp), dimension(12) tmp, real(dp), dimension(12) prc)
Definition at line 575 of file veg_dynamics.f90.
subroutine veg_dynamics::fire (real(dp), dimension(12,31) dprc, real(dp), dimension(12,31) dtmp, real(dp) fri, real(dp) fprob)
Definition at line 1018 of file veg_dynamics.f90.
References func::minx().
Referenced by cover().
subroutine veg_dynamics::grassrec (integer nft, real(dp), dimension(max_cohorts) ftprop, real(dp) gold, real(dp) x, integer, dimension(8) nat_map)
Definition at line 689 of file veg_dynamics.f90.
subroutine veg_dynamics::growth (integer nft, real(dp), dimension(max_cohorts) lai, real(dp) stembio, real(dp) rootbio, logical check_closure)
Definition at line 213 of file veg_dynamics.f90.
References state_methods::sum_carbon(), and thin().
Referenced by sdgvm().
subroutine veg_dynamics::initialise_new_cohorts (integer nft, real(dp), dimension(max_cohorts) ftprop, logical check_closure)
Definition at line 107 of file veg_dynamics.f90.
References state_methods::initialise_state_cohort(), state_methods::reset_soil_res(), state_methods::set_new_soil_res(), and state_methods::sum_carbon().
Referenced by sdgvm().
subroutine veg_dynamics::mklit (real(dp), dimension(max_cohorts) ftmat, real(dp), dimension(max_cohorts) slc, real(dp), dimension(max_cohorts) rlc, real(dp), dimension(max_cohorts) sln, real(dp), dimension(max_cohorts) rln, real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) nps, real(dp), dimension(max_cohorts) npr)
Definition at line 897 of file veg_dynamics.f90.
References stlit().
subroutine veg_dynamics::natural_veg (real(dp), dimension(12,31) tmp, real(dp), dimension(12,31) prc, real(dp), dimension(max_cohorts) ftprop, integer, dimension(8) nat_map)
Definition at line 1207 of file veg_dynamics.f90.
References func::minx(), and func::triscale().
Referenced by sdgvm1::set_landuse().
subroutine veg_dynamics::newgrowth (real(dp) fprob, real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) nps, integer fireres, real(dp) firec)
Definition at line 1103 of file veg_dynamics.f90.
References state_methods::accumulate_burnt_soil_res(), state_methods::accumulate_dist_soil_res(), and state_methods::compress_state().
Referenced by cover().
subroutine veg_dynamics::perc (character, dimension(100) fttags, real(dp), dimension(max_cohorts) dof, real(dp) tmin, real(dp), dimension(max_cohorts) ftprop, integer nft)
Definition at line 790 of file veg_dynamics.f90.
References func::ntags(), and func::triscale2().
real(dp) function veg_dynamics::stlit (real(dp) age, real(dp) mat)
Definition at line 932 of file veg_dynamics.f90.
Referenced by mklit(), and thin().
subroutine veg_dynamics::thin (integer nft, real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) lai, real(dp), dimension(max_cohorts) nps, real(dp), dimension(max_cohorts) evp, real(dp), dimension(max_cohorts) slc, logical check_closure)
Definition at line 291 of file veg_dynamics.f90.
References stlit(), and state_methods::sum_carbon().
Referenced by growth().
subroutine veg_dynamics::vegmat (integer nft, integer, dimension(max_cohorts) ftmor, real(dp), dimension(max_cohorts) ftwd, real(dp), dimension(max_cohorts) ftxyl, real(dp), dimension(max_cohorts) ftpd, real(dp), dimension(max_cohorts) evp, real(dp), dimension(max_cohorts) lai, real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) nps, real(dp), dimension(max_cohorts) ftmat)
Definition at line 967 of file veg_dynamics.f90.
The documentation for this module was generated from the following file:
src/veg_dynamics.f90