sdgvm: sdgvm1 Module Reference
sdgvm1 Module Reference
Public Member Functions
real(dp) function outputs (daily_out, ind, st1)
Compute outputs from daily_out.
subroutine set_landuse (ftprop, ilanduse, tmp, prc, nat_map, nft, cluse, year, yr0)
Set lanuse by allocating the cover of new ground.
subroutine set_climate (xtmpv, xprcv, xhumv, xcldv, withcloudcover, yearv, iyear, tmp, prc, hum, cld, thty_dys, yr0, year)
Set 'tmp' 'hum' 'prc' and 'cld'.
subroutine set_co2 (ca, spinl, iyear, speedc, co2, co2const, year, yr0)
Set CO2 value 'ca'.
subroutine read_landuse (stlu, ilanduse, yr0, yrf, du, nft, lat, lon, lutab, luse, cluse, l_lu)
subroutine read_climate (stinput, ststats, lat, lon, xlatf, xlatres, xlatresn, xlon0, xlonres, xlonresn, yr0, yrf, xtmpv, xhumv, xprcv, xcldv, isite, xyear0, xyearf, du, seed1, seed2, seed3, l_clim, l_stats, siteno, day_mnth, thty_dys, sit_grd, withcloudcover)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine get_input_filename (st1)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine country (stmask, lat, lon, country_name, country_id, l_regional)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine co2_0_f (co20, co2f, yearv, yr0, spinl, co2, co2const, nyears)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine read_soil (sttxdp, lat, lon, soil_chr, soil_chr2, du, l_soil)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine land_site_check (st1, st2, sites, lat_lon, latdel, londel, du, stmask)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine output_options (nomdos, otags, omav, ofmt)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine set_pixel_out (st1, st2, outyears, nomdos, otagsn, otags, oymd)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine set_subpixel_out (st1, st2, outyears, nomdos, otagsnft, otags, oymdft, out_cov, out_bio, out_bud, out_sen)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine mkdlit ()
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine sum_soilcn (soilc, soiln, minn)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine swap (ic0, in0, iminn, c0, n0, minn)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine mix_water (ftcov, nft)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Detailed Description
Definition at line 1 of file sdgvm1.f90.
Member Function/Subroutine Documentation
subroutine sdgvm1::co2_0_f (real(dp) co20, real(dp) co2f, integer, dimension(max_years) yearv, integer yr0, integer spinl, real(dp), dimension(max_years) co2, real(dp) co2const, integer nyears)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 599 of file sdgvm1.f90.
Referenced by sdgvm().
subroutine sdgvm1::country (character stmask, real(dp) lat, real(dp) lon, character country_name, integer country_id, logical l_regional)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 415 of file sdgvm1.f90.
References func::blank().
Referenced by sdgvm().
subroutine sdgvm1::get_input_filename (character st1)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 381 of file sdgvm1.f90.
subroutine sdgvm1::land_site_check (character st1, character st2, integer sites, real(dp), dimension(2000000,2) lat_lon, real(dp) latdel, real(dp) londel, integer du, character stmask)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 725 of file sdgvm1.f90.
References func::blank(), data::lorc(), and func::n_fields().
Referenced by read_input::read_input_file().
subroutine sdgvm1::mix_water (real(dp), dimension(max_cohorts) ftcov, integer nft)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 1259 of file sdgvm1.f90.
Referenced by sdgvm().
subroutine sdgvm1::mkdlit ()
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 1148 of file sdgvm1.f90.
Referenced by sdgvm().
subroutine sdgvm1::output_options (integer nomdos, character, dimension(100) otags, integer, dimension(50) omav, character, dimension(100) ofmt)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 778 of file sdgvm1.f90.
Referenced by read_input::read_input_file().
real(dp) function sdgvm1::outputs (real(dp), dimension(50,max_cohorts,12,31) daily_out, integer ind, character(len=3) st1)
Compute outputs from daily_out.
Four forms of outputs are available and are specified by 'st1' which can take any one of the values ['Add', 'Average', 'Max', 'Min'].
Author
Mark Lomas
Date
Feb 2006
Definition at line 29 of file sdgvm1.f90.
Referenced by sdgvm().
subroutine sdgvm1::read_climate (character stinput, character ststats, real(dp) lat, real(dp) lon, real(dp) xlatf, real(dp) xlatres, integer xlatresn, real(dp) xlon0, real(dp) xlonres, integer xlonresn, integer yr0, integer yrf, integer, dimension(500,12,31) xtmpv, integer, dimension(500,12,31) xhumv, integer, dimension(500,12,31) xprcv, integer, dimension(500,12) xcldv, integer isite, integer xyear0, integer xyearf, integer du, integer seed1, integer seed2, integer seed3, logical l_clim, logical l_stats, integer siteno, integer day_mnth, integer thty_dys, integer sit_grd, logical withcloudcover)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 325 of file sdgvm1.f90.
References data::ex_clim(), data::ex_clim_site(), and weather_generator::ex_clim_weather_generator().
Referenced by sdgvm().
subroutine sdgvm1::read_landuse (character stlu, integer ilanduse, integer yr0, integer yrf, integer du, integer nft, real(dp) lat, real(dp) lon, real(dp), dimension(255,100) lutab, integer, dimension(max_years) luse, real(dp), dimension(max_cohorts,max_years) cluse, logical l_lu)
Author
Mark Lomas
Date
Feb 2006
Definition at line 243 of file sdgvm1.f90.
References data::ex_clu(), data::ex_lu(), and func::ntags().
Referenced by sdgvm().
subroutine sdgvm1::read_soil (character sttxdp, real(dp) lat, real(dp) lon, real(dp), dimension(10) soil_chr, real(dp), dimension(10) soil_chr2, integer du, logical, dimension(20) l_soil)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 650 of file sdgvm1.f90.
References data::ex_soil().
Referenced by sdgvm().
subroutine sdgvm1::set_climate (integer, dimension(500,12,31) xtmpv, integer, dimension(500,12,31) xprcv, integer, dimension(500,12,31) xhumv, integer, dimension(500,12) xcldv, logical withcloudcover, integer, dimension(max_years) yearv, integer iyear, real(dp), dimension(12,31) tmp, real(dp), dimension(12,31) prc, real(dp), dimension(12,31) hum, real(dp), dimension(12) cld, integer thty_dys, integer yr0, integer year)
Set 'tmp' 'hum' 'prc' and 'cld'.
Assign climate from the raw data which is help in 'x???v' arrays.
Author
Mark Lomas
Date
Feb 2006
Definition at line 157 of file sdgvm1.f90.
References func::no_days().
Referenced by sdgvm().
subroutine sdgvm1::set_co2 (real(dp) ca, integer spinl, integer iyear, logical speedc, real(dp), dimension(max_years) co2, real(dp) co2const, integer year, integer yr0)
Set CO2 value 'ca'.
Author
Mark Lomas
Date
Feb 2006
Definition at line 206 of file sdgvm1.f90.
Referenced by sdgvm().
subroutine sdgvm1::set_landuse (real(dp), dimension(max_cohorts) ftprop, integer ilanduse, real(dp), dimension(12,31) tmp, real(dp), dimension(12,31) prc, integer, dimension(8) nat_map, integer nft, real(dp), dimension(max_cohorts,max_years) cluse, integer year, integer yr0)
Set lanuse by allocating the cover of new ground.
Assign gound available for new growth, through disturbance and mortality, given by ftprop. The values of the desired cover are given in the array 'cluse'. Note that any changes in the desired are only met if new ground is large enough to make up the difference. Over time the cover will reach any desired value and once reached the cover will remain constant.
Author
Mark Lomas
Date
Feb 2006
Definition at line 108 of file sdgvm1.f90.
References func::check_ft_grow(), and veg_dynamics::natural_veg().
Referenced by sdgvm().
subroutine sdgvm1::set_pixel_out (character st1, character st2, integer outyears, integer nomdos, integer, dimension(50) otagsn, character, dimension(100) otags, integer oymd)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 922 of file sdgvm1.f90.
References func::blank(), func::n_fields(), func::ntags(), func::stcmp(), func::stripb(), func::stripbn(), and func::stripbs().
Referenced by read_input::read_input_file().
subroutine sdgvm1::set_subpixel_out (character st1, character st2, integer outyears, integer nomdos, integer, dimension(50) otagsnft, character, dimension(100) otags, integer oymdft, logical out_cov, logical out_bio, logical out_bud, logical out_sen)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 1020 of file sdgvm1.f90.
References func::blank(), func::n_fields(), func::ntags(), func::stcmp(), func::stripb(), func::stripbn(), and func::stripbs().
Referenced by read_input::read_input_file().
subroutine sdgvm1::sum_soilcn (real(dp), dimension(max_cohorts) soilc, real(dp), dimension(max_cohorts) soiln, real(dp), dimension(max_cohorts) minn)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 1187 of file sdgvm1.f90.
Referenced by sdgvm().
subroutine sdgvm1::swap (real(dp), dimension(8) ic0, real(dp), dimension(8) in0, real(dp), dimension(3) iminn, real(dp), dimension(8) c0, real(dp), dimension(8) n0, real(dp), dimension(3) minn)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 1225 of file sdgvm1.f90.
The documentation for this module was generated from the following file:
src/sdgvm1.f90