sdgvm: read_input Module Reference
read_input Module Reference
Public Member Functions
subroutine read_input_file (buff1, stinput, stinit, stoutput, sttxdp, stmask, stlu, ststats, stco2, xlatf, xlon0, xlatres, xlonres, co2const, initise, initiseo, speedc, xspeedc, xseed1, spinl, yr0s, cycle, crand, yr0p, yrfp, outyears, nyears, yr0, yrf, yearind, idum, yearv, nomdos, otags, omav, ofmt, outyears1, outyears2, oymd, otagsn, otagsnft, snpshts, snp_no, out_cov, out_bio, out_bud, out_sen, lutab, grassrc, barerc, fireres, luse, l_b_and_c, soil_chr, topsl, defaulttopsl, sites, latdel, londel, lat_lon, day_mnth, thty_dys, xlatresn, xlonresn, ilanduse, nft, xyear0, xyearf, lmor_sc, oymdft, iofnft, sit_grd, du, narg)
subroutine read_param (stver)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Detailed Description
Definition at line 1 of file read_input.f90.
Member Function/Subroutine Documentation
subroutine read_input::read_input_file (character buff1, character stinput, character stinit, character stoutput, character sttxdp, character stmask, character stlu, character ststats, character stco2, real(dp) xlatf, real(dp) xlon0, real(dp) xlatres, real(dp) xlonres, real(dp) co2const, logical initise, logical initiseo, logical speedc, logical xspeedc, integer xseed1, integer spinl, integer yr0s, integer cycle, logical crand, integer yr0p, integer yrfp, integer outyears, integer nyears, integer yr0, integer yrf, integer, dimension(max_years) yearind, integer idum, integer, dimension(max_years) yearv, integer nomdos, character, dimension(100) otags, integer, dimension(50) omav, character, dimension(100) ofmt, integer outyears1, integer outyears2, integer oymd, integer, dimension(50) otagsn, integer, dimension(50) otagsnft, integer, dimension(1000) snpshts, integer snp_no, logical out_cov, logical out_bio, logical out_bud, logical out_sen, real(dp), dimension(255,100) lutab, real(dp) grassrc, real(dp) barerc, integer fireres, integer, dimension(max_years) luse, logical l_b_and_c, real(dp), dimension(10) soil_chr, real(dp) topsl, real(dp) defaulttopsl, integer sites, real(dp) latdel, real(dp) londel, real(dp), dimension(2000000,2) lat_lon, integer day_mnth, integer thty_dys, integer xlatresn, integer xlonresn, integer ilanduse, integer nft, integer xyear0, integer xyearf, real(dp), dimension(3600,max_cohorts) lmor_sc, integer oymdft, integer iofnft, integer sit_grd, integer du, integer narg)
Author
Mark Lomas
Date
Feb 2006
Definition at line 37 of file read_input.f90.
References func::blank(), sdgvm1::land_site_check(), data::landuse1(), func::n_fields(), func::ntags(), open_files::open_diag(), open_files::open_snapshots(), sdgvm1::output_options(), func::randomv(), sdgvm1::set_pixel_out(), sdgvm1::set_subpixel_out(), func::st2arr(), func::stcmp(), func::stripb(), func::stripbn(), and func::stripbs().
Referenced by sdgvm().
subroutine read_input::read_param (character stver)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 1087 of file read_input.f90.
References func::blank(), func::stcmp(), func::stripb(), and func::stripbs().
Referenced by sdgvm().
The documentation for this module was generated from the following file:
src/read_input.f90