sdgvm: weather_generator Module Reference
weather_generator Module Reference
Public Member Functions
subroutine ex_clim_weather_generator (stinput, ststats, lat, lon, xlatf, xlatres, xlatresn, xlon0, xlonres, xlonresn, yr0, yrf, tmpv, humv, prcv, mcldv, isite, year0, yearf, du, seed1, seed2, seed3, l_clim, l_stats)
subroutine read_wg_file (du, filename, ststats, values, lon, lat, l_stats)
real(dp) function floatingmean (day, mnth, year, lastyear, array)
subroutine rain_day_sub_fully_normalised (NO_RAIN_DAYS, RAIN_IN_MONTH, DAYS_IN_MONTH, SEED1, SEED2, SEED3, RAIN)
subroutine rain_day_sub_normalised (NO_RAIN_DAYS, RAIN_IN_MONTH, DAYS_IN_MONTH, SEED1, SEED2, SEED3, RAIN)
real(dp) function hum_day_mean2_fn (HUM_MEAN_MONTH, HUM_SD_MONTH, HUM_AUTOCORR_MONTH, HUM_YESTERDAY, IS1, IS2, IS3, NORMSWITCH)
Detailed Description
Definition at line 1 of file weather_generator.f90.
Member Function/Subroutine Documentation
subroutine weather_generator::ex_clim_weather_generator (character stinput, character ststats, real(dp) lat, real(dp) lon, real(dp) xlatf, real(dp) xlatres, integer xlatresn, real(dp) xlon0, real(dp) xlonres, integer xlonresn, integer yr0, integer yrf, integer, dimension(500,12,31) tmpv, integer, dimension(500,12,31) humv, integer, dimension(500,12,31) prcv, integer, dimension(500,12) mcldv, integer isite, integer year0, integer yearf, integer du, integer seed1, integer seed2, integer seed3, logical l_clim, logical l_stats)
Definition at line 15 of file weather_generator.f90.
References data::bi_lin(), func::blank(), floatingmean(), hum_day_mean2_fn(), rain_day_sub_fully_normalised(), read_wg_file(), func::round(), and metdos::temp_day_mean2_fn().
Referenced by sdgvm1::read_climate().
real(dp) function weather_generator::floatingmean (integer day, integer mnth, integer year, integer lastyear, integer, dimension(500,12) array)
Definition at line 427 of file weather_generator.f90.
Referenced by ex_clim_weather_generator().
real(dp) function weather_generator::hum_day_mean2_fn (real(dp) HUM_MEAN_MONTH, real(dp) HUM_SD_MONTH, real(dp) HUM_AUTOCORR_MONTH, real(dp) HUM_YESTERDAY, integer IS1, integer IS2, integer IS3, integer NORMSWITCH)
Definition at line 856 of file weather_generator.f90.
References metdos::norm_from_rand_fn().
Referenced by ex_clim_weather_generator().
subroutine weather_generator::rain_day_sub_fully_normalised (real(dp) NO_RAIN_DAYS, integer RAIN_IN_MONTH, integer DAYS_IN_MONTH, integer SEED1, integer SEED2, integer SEED3, real(dp), dimension(31) RAIN)
Definition at line 472 of file weather_generator.f90.
References metdos::gammadist_fn(), and metdos::rndf().
Referenced by ex_clim_weather_generator().
subroutine weather_generator::rain_day_sub_normalised (real(dp) NO_RAIN_DAYS, real(dp) RAIN_IN_MONTH, integer DAYS_IN_MONTH, integer SEED1, integer SEED2, integer SEED3, real(dp), dimension(31) RAIN)
Definition at line 616 of file weather_generator.f90.
References metdos::gammadist_fn(), and metdos::rndf().
subroutine weather_generator::read_wg_file (integer du, character filename, character ststats, real(dp), dimension(12) values, real(dp) lon, real(dp) lat, logical l_stats)
Definition at line 324 of file weather_generator.f90.
References data::bi_lin(), func::blank(), and func::stcmp().
Referenced by ex_clim_weather_generator().
The documentation for this module was generated from the following file:
src/weather_generator.f90