sdgvm: state_methods Module Reference
state_methods Module Reference
Public Member Functions
subroutine restrict_cohort_numbers ()
subroutine combine_cohorts (co1, co2)
subroutine make_co2ftmap (show)
subroutine remove_cohort (co)
subroutine initialise_state_cohort (cohort)
subroutine sum_carbon (total_carbon, show_all)
subroutine accumulate_dist_soil_res (ft, x)
subroutine accumulate_burnt_soil_res (ft, x, firec)
subroutine set_new_soil_res (ft, x)
subroutine reset_soil_res ()
subroutine initialise_state (initise, nft, cluse, xtmpv, soilt)
subroutine compress_state ()
subroutine ft_cover ()
subroutine set_misc_values (sla, t)
Detailed Description
Definition at line 1 of file state_methods.f90.
Member Function/Subroutine Documentation
subroutine state_methods::accumulate_burnt_soil_res (integer ft, real(dp) x, real(dp) firec)
Definition at line 638 of file state_methods.f90.
Referenced by veg_dynamics::newgrowth().
subroutine state_methods::accumulate_dist_soil_res (integer ft, real(dp) x)
Definition at line 586 of file state_methods.f90.
References initialise_state_cohort().
Referenced by veg_dynamics::newgrowth().
subroutine state_methods::combine_cohorts (integer co1, integer co2)
Definition at line 95 of file state_methods.f90.
References remove_cohort(), and sum_carbon().
Referenced by restrict_cohort_numbers().
subroutine state_methods::compress_state ()
Definition at line 930 of file state_methods.f90.
References initialise_state_cohort(), and make_co2ftmap().
Referenced by veg_dynamics::newgrowth().
subroutine state_methods::ft_cover ()
Definition at line 956 of file state_methods.f90.
subroutine state_methods::initialise_state (logical initise, integer nft, real(dp), dimension(max_cohorts,max_years) cluse, integer, dimension(500,12,31) xtmpv, real(dp) soilt)
Definition at line 772 of file state_methods.f90.
References make_co2ftmap(), and reset_soil_res().
Referenced by sdgvm().
subroutine state_methods::initialise_state_cohort (integer cohort)
Definition at line 432 of file state_methods.f90.
Referenced by accumulate_dist_soil_res(), compress_state(), and veg_dynamics::initialise_new_cohorts().
subroutine state_methods::make_co2ftmap (logical show)
Definition at line 359 of file state_methods.f90.
Referenced by compress_state(), initialise_state(), remove_cohort(), and restrict_cohort_numbers().
subroutine state_methods::remove_cohort (integer co)
Definition at line 398 of file state_methods.f90.
References make_co2ftmap().
Referenced by combine_cohorts().
subroutine state_methods::reset_soil_res ()
Definition at line 734 of file state_methods.f90.
Referenced by veg_dynamics::initialise_new_cohorts(), and initialise_state().
subroutine state_methods::restrict_cohort_numbers ()
Definition at line 22 of file state_methods.f90.
References combine_cohorts(), and make_co2ftmap().
Referenced by sdgvm().
subroutine state_methods::set_misc_values (real(dp) sla, real(dp) t)
Definition at line 975 of file state_methods.f90.
Referenced by sdgvm().
subroutine state_methods::set_new_soil_res (integer ft, real(dp) x)
Definition at line 700 of file state_methods.f90.
Referenced by veg_dynamics::initialise_new_cohorts().
subroutine state_methods::sum_carbon (real(dp) total_carbon, logical show_all)
Definition at line 529 of file state_methods.f90.
Referenced by combine_cohorts(), veg_dynamics::cover(), veg_dynamics::growth(), veg_dynamics::initialise_new_cohorts(), soil_methods::soil_dynamics(), and veg_dynamics::thin().
The documentation for this module was generated from the following file:
src/state_methods.f90