sdgvm: productivity_methods Module Reference
productivity_methods Module Reference
Public Member Functions
subroutine nppcalc (npp_eff, c3, maxc, soilc, soiln, minn, soil2g, wtwp, wtfc, rd, rlai, t, rh, ca, oi, rn, qdirect, qdiff, can2a, can2g, canres, suma, amx, amax, gsum, hrs, canga, p, day, nleaf_sum, fpr)
subroutine limitationprocess (av, pcv, gsv, aj, pcj, gsj, a, pc, gs)
subroutine assvmax (a, ci, cs, gs, oi, ca, vmx, rh, kg, ko, kc, tau, rd, ga, t, p)
subroutine assvmax3 (a, ci, cs, gs, oi, ca, vmx, rh, kg, ko, kc, tau, rd, ga, t, p, t154, xdvy, px, oitau1, oitau2, gsmin, kcoiko)
subroutine assj (a, ci, gs, oi, ca, rh, kg, tau, rd, ga, t, p, j)
subroutine assj3 (a, ci, gs, oi, ca, rh, kg, tau, rd, ga, t, p, j, t154, xdvy, px, oitau1, oitau2, gsmin)
subroutine assj4 (a, ci, gs, oi, ca, rh, kg, tau, rd, ga, t, p, j, t154, xdvy, px, oitau1, oitau2, gsmin)
subroutine assvmax2 (a, w, pc, gs, po, pa, vmax, g0, g1, rh, ko, kc, kg, tau, rd, acheck)
subroutine assj2 (a, w, pc, gs, po, pa, j, g0, g1, rh, kg, tau, rd, acheck)
subroutine xamax (a, xt, oi, vmx, rd, j, dresp, pc)
subroutine assc4 (a, pc, gs, pa, vmax, rh, t, qg, p, up)
subroutine assc42 (a, w, pc, gs, po, pa, vmax, g0, g1, rh, kg, tau, rd, t, qg, acheck, up)
subroutine xvjmax (vmx, jmx, j, xt, xq, sum, nup, oi, dresp)
Detailed Description
Definition at line 1 of file productivity_methods.f90.
Member Function/Subroutine Documentation
subroutine productivity_methods::assc4 (real(dp) a, real(dp) pc, real(dp) gs, real(dp) pa, real(dp) vmax, real(dp) rh, real(dp) t, real(dp) qg, real(dp) p, real(dp) up)
Definition at line 1157 of file productivity_methods.f90.
Referenced by nppcalc().
subroutine productivity_methods::assc42 (real(dp) a, real(dp) w, real(dp) pc, real(dp) gs, real(dp) po, real(dp) pa, real(dp) vmax, real(dp) g0, real(dp) g1, real(dp) rh, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) t, real(dp) qg, real(dp) acheck, real(dp) up)
Definition at line 1224 of file productivity_methods.f90.
subroutine productivity_methods::assj (real(dp) a, real(dp) ci, real(dp) gs, real(dp) oi, real(dp) ca, real(dp) rh, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p, real(dp) j)
Definition at line 704 of file productivity_methods.f90.
Referenced by assj3(), and assj4().
subroutine productivity_methods::assj2 (real(dp) a, real(dp) w, real(dp) pc, real(dp) gs, real(dp) po, real(dp) pa, real(dp) j, real(dp) g0, real(dp) g1, real(dp) rh, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) acheck)
Definition at line 998 of file productivity_methods.f90.
subroutine productivity_methods::assj3 (real(dp) a, real(dp) ci, real(dp) gs, real(dp) oi, real(dp) ca, real(dp) rh, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p, real(dp) j, real(dp) t154, real(dp) xdvy, real(dp) px, real(dp) oitau1, real(dp) oitau2, real(dp) gsmin)
Definition at line 809 of file productivity_methods.f90.
References assj().
Referenced by nppcalc().
subroutine productivity_methods::assj4 (real(dp) a, real(dp) ci, real(dp) gs, real(dp) oi, real(dp) ca, real(dp) rh, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p, real(dp) j, real(dp) t154, real(dp) xdvy, real(dp) px, real(dp) oitau1, real(dp) oitau2, real(dp) gsmin)
Definition at line 855 of file productivity_methods.f90.
References assj().
Referenced by nppcalc().
subroutine productivity_methods::assvmax (real(dp) a, real(dp) ci, real(dp) cs, real(dp) gs, real(dp) oi, real(dp) ca, real(dp) vmx, real(dp) rh, real(dp) kg, real(dp) ko, real(dp) kc, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p)
Definition at line 541 of file productivity_methods.f90.
Referenced by assvmax3().
subroutine productivity_methods::assvmax2 (real(dp) a, real(dp) w, real(dp) pc, real(dp) gs, real(dp) po, real(dp) pa, real(dp) vmax, real(dp) g0, real(dp) g1, real(dp) rh, real(dp) ko, real(dp) kc, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) acheck)
Definition at line 901 of file productivity_methods.f90.
subroutine productivity_methods::assvmax3 (real(dp) a, real(dp) ci, real(dp) cs, real(dp) gs, real(dp) oi, real(dp) ca, real(dp) vmx, real(dp) rh, real(dp) kg, real(dp) ko, real(dp) kc, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p, real(dp) t154, real(dp) xdvy, real(dp) px, real(dp) oitau1, real(dp) oitau2, real(dp) gsmin, real(dp) kcoiko)
Definition at line 658 of file productivity_methods.f90.
References assvmax().
Referenced by nppcalc().
subroutine productivity_methods::limitationprocess (real(dp) av, real(dp) pcv, real(dp) gsv, real(dp) aj, real(dp) pcj, real(dp) gsj, real(dp) a, real(dp) pc, real(dp) gs)
Definition at line 502 of file productivity_methods.f90.
Referenced by nppcalc().
subroutine productivity_methods::nppcalc (real(dp) npp_eff, integer c3, real(dp) maxc, real(dp) soilc, real(dp) soiln, real(dp) minn, real(dp) soil2g, real(dp) wtwp, real(dp) wtfc, real(dp) rd, real(dp) rlai, real(dp) t, real(dp) rh, real(dp) ca, real(dp) oi, real(dp) rn, real(dp) qdirect, real(dp) qdiff, real(dp) can2a, real(dp) can2g, real(dp) canres, real(dp) suma, real(dp) amx, real(dp) amax, real(dp) gsum, real(dp) hrs, real(dp) canga, real(dp) p, integer day, real(dp) nleaf_sum, real(dp) fpr)
Definition at line 25 of file productivity_methods.f90.
References assc4(), assj3(), assj4(), assvmax3(), sunshade::goudriaanslaw2(), and limitationprocess().
Referenced by doly::dolyday().
subroutine productivity_methods::xamax (real(dp) a, real(dp) xt, real(dp) oi, real(dp) vmx, real(dp) rd, real(dp) j, real(dp) dresp, real(dp) pc)
Definition at line 1089 of file productivity_methods.f90.
subroutine productivity_methods::xvjmax (real(dp) vmx, real(dp) jmx, real(dp) j, real(dp) xt, real(dp) xq, real(dp) sum, real(dp) nup, real(dp) oi, real(dp) dresp)
Definition at line 1386 of file productivity_methods.f90.
The documentation for this module was generated from the following file:
src/productivity_methods.f90