sdgvm: doly Module Reference
doly Module Reference
Collection of subroutines to read in data.
Public Member Functions
subroutine dolyday (tmp, prc, hum, ca, soilc, soiln, minn, adp, sfc, sw, sswc, awl, kd, kx, daygpp, resp_l, rlai, evap, tran, roff, interc, evbs, flow1, flow2, year, mnth, day, pet, ht, thty_dys, ft, lmor_sc, nleaf, leaflitter, hrs, q, qdirect, qdiff, fpr, canga, gsn, rn, check_closure)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine evapotranspiration (t, rh, rn, canga, gsn, hrs, eemm, etmm)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Detailed Description
Collection of subroutines to read in data.
Author
Mark Lomas
Date
July 2016
Definition at line 6 of file doly.f90.
Member Function/Subroutine Documentation
subroutine doly::dolyday (real(dp) tmp, real(dp) prc, real(dp) hum, real(dp) ca, real(dp) soilc, real(dp) soiln, real(dp) minn, real(dp), dimension(4) adp, real(dp), dimension(4) sfc, real(dp), dimension(4) sw, real(dp), dimension(4) sswc, real(dp), dimension(4) awl, real(dp) kd, real(dp) kx, real(dp) daygpp, real(dp) resp_l, real(dp) rlai, real(dp) evap, real(dp) tran, real(dp) roff, real(dp) interc, real(dp) evbs, real(dp) flow1, real(dp) flow2, integer year, integer mnth, integer day, real(dp) pet, real(dp) ht, integer thty_dys, integer ft, real(dp), dimension(3600) lmor_sc, real(dp) nleaf, real(dp) leaflitter, real(dp) hrs, real(dp) q, real(dp) qdirect, real(dp) qdiff, real(dp) fpr, real(dp) canga, real(dp) gsn, real(dp) rn, logical check_closure)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 37 of file doly.f90.
References veg_dynamics::c3c4(), productivity_methods::nppcalc(), and phenology_methods::suma_add().
Referenced by sdgvm().
subroutine doly::evapotranspiration (real(dp) t, real(dp) rh, real(dp) rn, real(dp) canga, real(dp) gsn, real(dp) hrs, real(dp) eemm, real(dp) etmm)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 339 of file doly.f90.
Referenced by sdgvm().
The documentation for this module was generated from the following file:
src/doly.f90