sdgvm: open_files Module Reference
open_files Module Reference
Public Member Functions
subroutine open_diag (stoutput)
Open diagnostic file.
subroutine open_snapshots (stoutput, snp_no, snpshts)
Open snapshot files file.
subroutine open_default (stoutput)
Open default output files.
subroutine open_optional (stoutput, nft, out_cov, out_bio, out_bud, out_sen)
Open optional output files.
subroutine open_state (stinit, stoutput, initise, initiseo)
Open input and/or output files for state vector.
subroutine write_lat_lon (lat, lon, nft, out_cov, out_bio, out_bud, out_sen, oymdft, otagsn, oymd, otagsnft, outyears1, outyears2)
Write lat & lon for output files.
Detailed Description
Definition at line 1 of file open_files.f90.
Member Function/Subroutine Documentation
subroutine open_files::open_default (character stoutput)
Open default output files.
These files will contain yearly values.
Author
Mark Lomas
Date
Feb 2006
Definition at line 104 of file open_files.f90.
References func::blank().
Referenced by sdgvm().
subroutine open_files::open_diag (character stoutput)
Open diagnostic file.
This is used to report any potential errors.
Author
Mark Lomas
Date
Feb 2006
Definition at line 23 of file open_files.f90.
References func::blank().
Referenced by read_input::read_input_file().
subroutine open_files::open_optional (character stoutput, integer nft, logical out_cov, logical out_bio, logical out_bud, logical out_sen)
Open optional output files.
Author
Mark Lomas
Date
Feb 2006
Definition at line 159 of file open_files.f90.
References func::blank().
Referenced by sdgvm().
subroutine open_files::open_snapshots (character stoutput, integer snp_no, integer, dimension(1000) snpshts)
Open snapshot files file.
These files contain the entire system state for the final day of the years given in the input files. The files can be used the make site 'cartoons' using the utility sorfware.
Author
Mark Lomas
Date
Feb 2006
Definition at line 59 of file open_files.f90.
References func::blank(), func::in2st(), and func::stripb().
Referenced by read_input::read_input_file().
subroutine open_files::open_state (character stinit, character stoutput, logical initise, logical initiseo)
Open input and/or output files for state vector.
Author
Mark Lomas
Date
Feb 2006
Definition at line 211 of file open_files.f90.
References func::blank().
Referenced by sdgvm().
subroutine open_files::write_lat_lon (real(dp) lat, real(dp) lon, integer nft, logical out_cov, logical out_bio, logical out_bud, logical out_sen, integer oymdft, integer, dimension(50) otagsn, integer oymd, integer, dimension(50) otagsnft, integer outyears1, integer outyears2)
Write lat & lon for output files.
Author
Mark Lomas
Date
Feb 2006
Definition at line 275 of file open_files.f90.
Referenced by sdgvm().
The documentation for this module was generated from the following file:
src/open_files.f90