sdgvm: func Module Reference
func Module Reference
Public Member Functions
integer function check_ft_grow (tmp, xchill, xdschill, ft)
integer function minx (x)
real(dp) function dfn (age, mature)
real(dp) function ttg (i, ttglim)
real(dp) function triscale2 (x, y, x1, x2, x3, y1, y2, y3)
real(dp) function triscale (x, x1, x2, x3)
integer function no_days (year, mnth, thty_dys)
integer function no_day (year, mnth, day, thty_dys)
subroutine st2arr (st1, x, ix, no)
subroutine stripbn (st1, ans)
subroutine stripbs (st1, st2)
subroutine stripb (st1)
integer function blank (st1)
integer function last_blank (st1)
integer function blanks (st1)
integer function n_fields (st1)
character(1000) function in2st (int1)
integer function ntags (st1, st2)
integer function stcmp (st1, st2)
subroutine randomv (years, yr0, yrf, idum)
integer function ranv (i, j, idum)
real(dp) function ran1 (idum)
integer function round (x)
subroutine matcheck (x, a, b, c, d, check, ind, n)
subroutine pile4 (x, a, b, c, d, n)
subroutine pile1 (x, a, n)
Detailed Description
Definition at line 1 of file func.f90.
Member Function/Subroutine Documentation
integer function func::blank (character st1)
Definition at line 490 of file func.f90.
Referenced by sdgvm1::country(), data::ex_clim(), data::ex_clim_site(), weather_generator::ex_clim_weather_generator(), data::ex_clu(), data::ex_lu(), data::ex_soil(), sdgvm1::land_site_check(), data::lorc(), open_files::open_default(), open_files::open_diag(), open_files::open_optional(), open_files::open_snapshots(), open_files::open_state(), read_input::read_input_file(), read_input::read_param(), weather_generator::read_wg_file(), data::readco2(), sdgvm(), sdgvm1::set_pixel_out(), sdgvm1::set_subpixel_out(), stripbn(), and stripbs().
integer function func::blanks (character st1)
Definition at line 550 of file func.f90.
Referenced by n_fields(), stripb(), stripbn(), and stripbs().
integer function func::check_ft_grow (real(dp), dimension(12,31) tmp, integer xchill, integer xdschill, integer ft)
Definition at line 17 of file func.f90.
Referenced by sdgvm1::set_landuse().
real(dp) function func::dfn (integer age, real(dp) mature)
Definition at line 128 of file func.f90.
character(1000) function func::in2st (integer int1)
Definition at line 615 of file func.f90.
Referenced by data::ex_clu(), and open_files::open_snapshots().
integer function func::last_blank (character st1)
Definition at line 520 of file func.f90.
Referenced by sdgvm().
subroutine func::matcheck (real(dp), dimension(n,4) x, real(dp) a, real(dp) b, real(dp) c, real(dp) d, real(dp) check, integer ind, integer n)
Definition at line 863 of file func.f90.
integer function func::minx (real(dp), dimension(12) x)
Definition at line 97 of file func.f90.
Referenced by veg_dynamics::fire(), and veg_dynamics::natural_veg().
integer function func::n_fields (character st1)
Definition at line 582 of file func.f90.
References blanks(), and stripbs().
Referenced by data::ex_clu(), data::ex_lu(), sdgvm1::land_site_check(), read_input::read_input_file(), sdgvm1::set_pixel_out(), and sdgvm1::set_subpixel_out().
integer function func::no_day (integer year, integer mnth, integer day, integer thty_dys)
Definition at line 290 of file func.f90.
References no_days().
Referenced by sdgvm().
integer function func::no_days (integer year, integer mnth, integer thty_dys)
Definition at line 249 of file func.f90.
Referenced by data::ex_clim_site(), no_day(), sdgvm(), and sdgvm1::set_climate().
integer function func::ntags (character, dimension(100) st1, character st2)
Definition at line 650 of file func.f90.
References stcmp().
Referenced by veg_dynamics::perc(), read_input::read_input_file(), sdgvm1::read_landuse(), sdgvm1::set_pixel_out(), and sdgvm1::set_subpixel_out().
subroutine func::pile1 (real(dp), dimension(n) x, real(dp) a, integer n)
Definition at line 932 of file func.f90.
subroutine func::pile4 (real(dp), dimension(n,4) x, real(dp) a, real(dp) b, real(dp) c, real(dp) d, integer n)
Definition at line 897 of file func.f90.
real(dp) function func::ran1 (integer idum)
Definition at line 776 of file func.f90.
Referenced by ranv().
subroutine func::randomv (integer, dimension(yrf-yr0+1) years, integer yr0, integer yrf, integer idum)
Definition at line 721 of file func.f90.
References ranv().
Referenced by read_input::read_input_file().
integer function func::ranv (integer i, integer j, integer idum)
Definition at line 754 of file func.f90.
References ran1().
Referenced by randomv().
integer function func::round (real(dp) x)
Definition at line 822 of file func.f90.
Referenced by weather_generator::ex_clim_weather_generator().
subroutine func::st2arr (character st1, integer, dimension(ix) x, integer ix, integer no)
Definition at line 321 of file func.f90.
References stripbn().
Referenced by data::ex_clu(), data::ex_lu(), and read_input::read_input_file().
integer function func::stcmp (character st1, character st2)
Definition at line 685 of file func.f90.
Referenced by data::ex_clu(), ntags(), read_input::read_input_file(), read_input::read_param(), weather_generator::read_wg_file(), sdgvm1::set_pixel_out(), and sdgvm1::set_subpixel_out().
subroutine func::stripb (character st1)
Definition at line 455 of file func.f90.
References blanks().
Referenced by data::ex_clu(), open_files::open_snapshots(), read_input::read_input_file(), read_input::read_param(), sdgvm(), sdgvm1::set_pixel_out(), and sdgvm1::set_subpixel_out().
subroutine func::stripbn (character st1, integer ans)
Definition at line 354 of file func.f90.
References blank(), and blanks().
Referenced by read_input::read_input_file(), sdgvm1::set_pixel_out(), sdgvm1::set_subpixel_out(), and st2arr().
subroutine func::stripbs (character st1, character st2)
Definition at line 408 of file func.f90.
References blank(), and blanks().
Referenced by n_fields(), read_input::read_input_file(), read_input::read_param(), sdgvm1::set_pixel_out(), and sdgvm1::set_subpixel_out().
real(dp) function func::triscale (real(dp) x, real(dp) x1, real(dp) x2, real(dp) x3)
Definition at line 218 of file func.f90.
Referenced by veg_dynamics::natural_veg().
real(dp) function func::triscale2 (real(dp) x, real(dp) y, real(dp) x1, real(dp) x2, real(dp) x3, real(dp) y1, real(dp) y2, real(dp) y3)
Definition at line 181 of file func.f90.
Referenced by veg_dynamics::perc().
real(dp) function func::ttg (integer i, integer ttglim)
Definition at line 157 of file func.f90.
The documentation for this module was generated from the following file:
src/func.f90