sdgvm: data Module Reference
data Module Reference
Collection of subroutines to read in data.
Public Member Functions
subroutine ex_clim (stinput, lat, lon, xlatf, xlatres, xlatresn, xlon0, xlonres, xlonresn, yr0, yrf, tmpv, humv, prcv, isite, year0, yearf, siteno, du)
Extract climate data from the climate database for the nearest site.
subroutine ex_clim_site (stinput, yr0, yrf, tmpv, humv, prcv, year0, yearf)
Extract climate data from the climate database for the nearest site.
subroutine ex_soil (fname1, lat, lon, sol_chr2, du, l_soil)
Extract % sand % silt bulk density and depth from soils database.
subroutine ex_lu (fname1, lat, lon, luse, yr0, yrf, du)
Extract land use.
subroutine ex_clu (fname1, lat, lon, nft, lutab, cluse, yr0, yrf, du, l_lu)
subroutine lorc (du, lat, lon, latdel, londel, stmask, xx)
Determine if the site is a land site.
subroutine base72i (c, x)
integer function n7 (x)
subroutine bi_lin (xx, indx, xnorm, ynorm, ans)
Performs bilinear interpolation between four points.
subroutine readco2 (stco2, yr0, yrf, co2)
subroutine landuse1 (luse, yr0, yrf)
Detailed Description
Collection of subroutines to read in data.
Author
Mark Lomas
Date
July 2016
Definition at line 6 of file data.f90.
Member Function/Subroutine Documentation
subroutine data::base72i (character c, integer, dimension(7) x)
Author
Mark Lomas
Date
Feb 2006
Definition at line 892 of file data.f90.
Referenced by lorc().
subroutine data::bi_lin (real(dp), dimension(4,4) xx, integer, dimension(4,4) indx, real(dp) xnorm, real(dp) ynorm, real(dp) ans)
Performs bilinear interpolation between four points.
Performs bilinear interpolation between four points, the normalised distances from the point (1,1) are given by 'xnorm' and 'ynorm'.
Author
Mark Lomas
Date
Feb 2006
Definition at line 965 of file data.f90.
Referenced by weather_generator::ex_clim_weather_generator(), ex_clu(), ex_soil(), and weather_generator::read_wg_file().
subroutine data::ex_clim (character stinput, real(dp) lat, real(dp) lon, real(dp) xlatf, real(dp) xlatres, integer xlatresn, real(dp) xlon0, real(dp) xlonres, integer xlonresn, integer yr0, integer yrf, integer, dimension(300,12,31) tmpv, integer, dimension(300,12,31) humv, integer, dimension(300,12,31) prcv, integer isite, integer year0, integer yearf, integer siteno, integer du)
Extract climate data from the climate database for the nearest site.
Author
Mark Lomas
Date
Feb 2006
! Extract climate data from the climate database for the nearest site to lat,lon, replace lat,lon with the nearest cell from the database.
       UNIX                DOS
       ii(4)               ii(5)   for beginning of binary file
                                   records
       recl = 728          recl = 730     for binary climate
       recl = 577          recl = 578     for text map
Author
Mark Lomas
Date
Feb 2006
Definition at line 49 of file data.f90.
References func::blank().
Referenced by sdgvm1::read_climate().
subroutine data::ex_clim_site (character stinput, integer yr0, integer yrf, integer, dimension(300,12,31) tmpv, integer, dimension(300,12,31) humv, integer, dimension(300,12,31) prcv, integer year0, integer yearf)
Extract climate data from the climate database for the nearest site.
Extract climate data from the climate database for the nearest site to lat,lon, replace lat,lon with the nearest cell from the database.
       UNIX                DOS
       ii(4)               ii(5)   for beginning of binary file
                                   records
       recl = 728          recl = 730     for binary climate
       recl = 577          recl = 578     for text map
Author
Mark Lomas
Date
Feb 2006
Definition at line 181 of file data.f90.
References func::blank(), and func::no_days().
Referenced by sdgvm1::read_climate().
subroutine data::ex_clu (character fname1, real(dp) lat, real(dp) lon, integer nft, real(dp), dimension(255,100) lutab, real(dp), dimension(max_cohorts,max_years) cluse, integer yr0, integer yrf, integer du, logical l_lu)
Extract land use from land use soils database for the nearest site to lat,lon, replace lat,lon with the nearest cell from the database. The data contains the percent (in byte format) for each pft from 2 to nft
Author
Mark Lomas
Date
Feb 2006
Definition at line 594 of file data.f90.
References bi_lin(), func::blank(), func::in2st(), func::n_fields(), func::st2arr(), func::stcmp(), and func::stripb().
Referenced by sdgvm1::read_landuse().
subroutine data::ex_lu (character fname1, real(dp) lat, real(dp) lon, integer, dimension(max_years) luse, integer yr0, integer yrf, integer du)
Extract land use.
Extract land use from land use soils database for the nearest site to lat,lon, replace lat,lon with the nearest cell from the database.
Author
Mark Lomas
Date
Feb 2006
Definition at line 445 of file data.f90.
References func::blank(), func::n_fields(), and func::st2arr().
Referenced by sdgvm1::read_landuse().
subroutine data::ex_soil (character fname1, real(dp) lat, real(dp) lon, real(dp), dimension(10) sol_chr2, integer du, logical, dimension(20) l_soil)
Extract % sand % silt bulk density and depth from soils database.
Extract % sand % silt bulk density and depth from soils database.
Author
Mark Lomas
Date
Feb 2006
Definition at line 233 of file data.f90.
References bi_lin(), and func::blank().
Referenced by sdgvm1::read_soil().
subroutine data::landuse1 (integer, dimension(max_years) luse, integer yr0, integer yrf)
Author
Mark Lomas
Date
Feb 2006
Definition at line 1100 of file data.f90.
Referenced by read_input::read_input_file().
subroutine data::lorc (integer du, real(dp) lat, real(dp) lon, real(dp) latdel, real(dp) londel, character stmask, logical xx)
Determine if the site is a land site.
Using a half an arc-second land sea mask. Determine whether the site is land or sea based on the majority of the mask within the limits of the gridcell.
Author
Mark Lomas
Date
Feb 2006
Definition at line 783 of file data.f90.
References base72i(), and func::blank().
Referenced by sdgvm1::land_site_check().
integer function data::n7 (integer, dimension(7) x)
Author
Mark Lomas
Date
Feb 2006
Definition at line 935 of file data.f90.
subroutine data::readco2 (character stco2, integer yr0, integer yrf, real(dp), dimension(max_years) co2)
Author
Mark Lomas
Date
Feb 2006
Definition at line 1049 of file data.f90.
References func::blank().
Referenced by sdgvm().
The documentation for this module was generated from the following file:
src/data.f90